spirit = True
flesh = False
print(spirit and flesh)
print(spirit or flesh)
print(not spirit)
print(spirit and not flesh)

print("-------------")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("-------------")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("-------------")
print(not True)
print(not False)