print("alnum     : 123abc  : " +  str("123abc".isalnum()))
print("alnum     : 123abc# : " +  str("123abc#".isalnum()))
print("alpha     : abcDδΔ  : " +  str("abcDδΔ".isalpha()))
print("alpha     : δαες12  : " +  str("δαες12".isalpha()))
print("digit     : 123456  : " +  str("123456".isdigit()))
print("digit     : 123a34  : " +  str("123a34".isdigit()))
print("space     :         : " +  str("    ".isspace()))
print("printable : aA12 #  : " +  str("aA12 #".isprintable()))
print("printable : \\na    : " +  str("\na   ".isprintable()))
print("identifier: is_var  : " +  str("is_var".isidentifier()))
print("identifier: 12ar    : " +  str("12ar".isidentifier()))
print("lower     : abca34  : " +  str("abca34".islower()))
print("upper     : ABFa34  : " +  str("ABFa34".isupper()))
print("title     : Tik Tok : " +  str("Tik Tok".istitle()))